from discord.ext import commands
import discord
from discord.commands import Option, slash_command, message_command
from utilities import openai
from utilities.logging import logger

class OpenAI(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    def get_name(self, user):
        if not user.global_name == None:
            uname = user.global_name
        elif not user.nick == None:
            uname = user.nick
        else:
            uname = user.name
        return uname
    
    @message_command(name="Roast This Message")
    async def roast(self, ctx, message: discord.Message):
        await ctx.defer()
        uname = self.get_name(message.author)
        req_uname = self.get_name(ctx.user)
        channel_name = ctx.channel.name
        async with ctx.channel.typing():
            response = openai.generate_roast(message.content, uname)
            log_msg = f"\nAI roast generated by {req_uname} in {channel_name} on {uname}'s message\n\n"
            log_msg = log_msg + f"Message:\n\t{message.content}\n\n"
            log_msg = log_msg + f"Roast:\n\t{response}"
            logger.info(log_msg)
            await ctx.respond(response)


    @slash_command(
        default_permissions=True,
        description="Ask CHHBot a question (Beta)",
    )
    async def ask(self, ctx: discord.ApplicationContext, prompt: Option(str, 'Prompt for CHHBot', required=True), hide: Option(bool, "Do you want this to show only for you?", required=False, default=False)):
        await ctx.defer(ephemeral=hide)
        uname = self.get_name(ctx.user)
        channel_name = ctx.channel.name
        if not hide:
            async with ctx.channel.typing():
                response = openai.generate_answer(prompt, uname=uname)
                response = f"{uname} asked: \n{prompt}\n---\n" + response
                log_msg = f"\nAI response generated by {uname} in {channel_name}\n\n"
                log_msg = log_msg + f"Prompt:\n\t{prompt}\n\n"
                log_msg = log_msg + f"Response:\n\t{response}"
                logger.info(log_msg)
        else:
            response = openai.generate_answer(prompt, uname=uname)
            log_msg = f"\nHidden AI response generated by {uname}\n\n"
            log_msg = log_msg + f"Prompt: \n\t{prompt}\n\n"
            log_msg = log_msg + f"Response: \n\t{response}"
            logger.info(log_msg)
        await ctx.respond(response, ephemeral=hide)
def setup(bot):
    bot.add_cog(OpenAI(bot))